-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.books
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    quantity integer NOT NULL,
    description text COLLATE pg_catalog."default",
    book_id serial NOT NULL,
    genre character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT books_pkey PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    order_date date NOT NULL DEFAULT CURRENT_DATE,
    price numeric(10, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Completed'::character varying,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.rentals
(
    rental_id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    rental_start date NOT NULL,
    rental_due date NOT NULL,
    rental_returned date,
    fine numeric(10, 2) DEFAULT 0,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    CONSTRAINT rentals_pkey PRIMARY KEY (rental_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_no bigint NOT NULL,
    dob date,
    is_restricted boolean DEFAULT false,
    is_admin boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.wallets
(
    wallet_id serial NOT NULL,
    user_id integer NOT NULL,
    balance numeric(10, 2) DEFAULT 0.0,
    CONSTRAINT wallets_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT wallets_user_id_key UNIQUE (user_id)
);
END;